services:
#    x_team_slack_messanger.example:
#        class: XTeam\SlackMessengerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


     x_team_slack_messenger.slack.api.client:
         class:  CL\Slack\Transport\ApiClient
         arguments:
            - %slack.token%
            - ~
            - ~
            - ~
            - @event_dispatcher

     x_team_slack_messenger.builder.api_slack_message_builder:
         class: XTeam\SlackMessengerBundle\Builder\SlackAPIMessageBuilder

     x_team_slack_messenger.controller.message:
         class: XTeam\SlackMessengerBundle\Controller\MessageController
         arguments:
            - @event_dispatcher
            - @x_team_slack_messenger.builder.api_slack_message_builder
