services:
     x_team_slack_messenger.slack.api.client:
         class:  CL\Slack\Transport\ApiClient
         arguments:
            - %slack.token%
            - ~
            - ~
            - ~
            - @event_dispatcher

     x_team_slack_messenger.builder.api_slack_message_builder:
         class: XTeam\SlackMessengerBundle\Builder\SlackAPIMessageBuilder

     x_team_slack_messenger.builder.slack_api_user_builder:
         class: XTeam\SlackMessengerBundle\Builder\SlackAPIUserBuilder

     x_team_slack_messenger.controller.message:
         class: XTeam\SlackMessengerBundle\Controller\MessageController
         arguments:
            - @event_dispatcher
            - @x_team_slack_messenger.builder.api_slack_message_builder
